### ISSUE TITLE
No TravelTime bound for mode ride - 10 pct scenario

### ISSUE THREAD

**Issue by kiranramnath007** [matsim-vsp/matsim-berlin#10]
When I try to run the 10 pct scenario, I get the following error (I do not encounter this for the 1 pct scenario). Any leads?

'<addr>' Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: No TravelTime bound for mode ride.
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=ride)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=124, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:109)
  while locating org.matsim.core.router.TripRouter

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
        at org.matsim.analysis.ModeStatsControlerListener.notifyStartup(ModeStatsControlerListener.java:115)
        at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:108)
        at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:77)
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
        at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
'</addr>'

**Comment by ikaddoura** [comment]
I can't reproduce your error. I cloned the project and started runs for the 10pct and 1pct scenario without having any problems. Make sure that you use the exact same run class "RunBerlinScenario" because this is where the travel time is bound for the ride mode...

**Comment by kiranramnath007** [comment]
I realized that I only encounter this problem when I try to run the jar file from the command line for both scenarios (encountered it for the 10 pct scenario while running it on a server). 

The command I used is 

` java -Xmx28000m -cp ./matsim-berlin-5.3-jar-with-dependencies.jar org.matsim.run.Controler ./scenarios/berlin-v5.3-1pct/input/berlin-v5.3-1pct.config.xml  `

Should I be specifying additional arguments for the injection to work as expected?

**Comment by ikaddoura** [comment]
It seems that you are using the default controler: org.matsim.run.Controler. Instead, please use the berlin-specific controler: org.matsim.run.RunBerlinScenario

The problem should appear for both the 1pct and the 10pct scenario, maybe you use different scripts on the server vs. local.

**Comment by kiranramnath007** [comment]
Yes the problem does appear for both scenarios from the command-line with the earlier command. Thanks for the recommendation, it worked.

Another question unrelated to the issue - can we use contribs or extensions directly with Berlin Scenario?

**Comment by ikaddoura** [comment]
Welcome.

For contribs, use your IDE and simply modify the run class "RunBerlinScenario". Alternatively, write your own run class and import RunBerlinScenario via jitpack: https://jitpack.io/#matsim-vsp/matsim-berlin

In your own run class, please use the RunBerlinScenario class to prepare your controler:

`RunBerlinScenario berlin = new RunBerlinScenario
Controler controler = berlin.prepareControler()`
