### ISSUE TITLE
Error in running the 1% scenario through jar

### ISSUE THREAD

**Issue by vasilis-mourtakos** [matsim-vsp/matsim-berlin#12]
I just run the 1pct scenario through the provided jar file, i selected the config file and increased the memory to 8gb. The program run from 00.45 to 10.26 when it gave out the following error:

ERROR MatsimRuntimeModifications$1:41 Getting uncaught Exception in Thread main
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.matsim.core.controler.corelisteners.DumpDataAtEndImpl.dumpLanes(DumpDataAtEndImpl.java:200)
	at org.matsim.core.controler.corelisteners.DumpDataAtEndImpl.notifyShutdown(DumpDataAtEndImpl.java:131)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerShutdownEvent(ControlerListenerManagerImpl.java:122)
	at org.matsim.core.controler.AbstractController$1.shutdown(AbstractController.java:85)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:66)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:234)
	at org.matsim.run.RunBerlinScenario.run(RunBerlinScenario.java:201)
	at org.matsim.run.RunBerlinScenario.main(RunBerlinScenario.java:70)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more

This is the full log file: https://www.dropbox.com/s/uu87vrokvfe74ta/berlin-v5.3-1pct.logfile.log?dl=0

How to deal with this error? I am a begginer in MATSim and I'm trying to use it for my thesis to simulate the effects of the implemetation of autonomous vehicles and robotaxis in the daily traffic. So any advice in that direction would also be much appreciated!!

Thanks in advance,
Vasilis M.

**Comment by michalmac** [comment]
I guess you are using JDK 9+

@ikaddoura , there should be something like this added to pom.xml (probably to all 3 branches):
https://github.com/matsim-org/matsim/blob/a829a99e7fdf22e499bb899c58891c92f3891102/contribs/pom.xml#L301-L323

Once it's there, you need to enable the java-9+ maven profile in the IDE -- at least if you are running the scenario in IntelliJ.

**Comment by vasilis-mourtakos** [comment]
I checked my java version and I'm have:
C:\Windows\System32>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

I haven't used an IDE to run MATSim yet (I just used the jar file to have a first look on how the scenario works). Should I run the scenarios on an IDE (I have set up a MATSim project on Eclipse) in order to check and adapt them for my simulations or can I just use the jar file?

**Comment by ikaddoura** [comment]
Thanks @michalmac. I changed the pom in the development branch 5.4.x. Will change it for the other branches as well in the coming days. But since @vasilis-mourtakos's java version was 1.8, this may not have caused the exception...?

@vasilis-mourtakos:
* No, running the scenario (branch 5.3.x) with the jar file should be fine. If you want to try the latest changes in the development branch (5.4.x), there is no way of getting around an IDE / building your own jar...
* According to your logfile, the error appears at the very end of the simulation, all important files should have already been written out. For testing, you might just set the number of iterations to 1 to see whether the error still appears.

**Comment by michalmac** [comment]
@vasilis-mourtakos for me this is a typical JDK9+ issue. Please double check if you have more than 1 jre/jdk installed

**Comment by vasilis-mourtakos** [comment]
Ok, thanks both of you a lot for the replies. I will check everything you mentioned and hopefully make some progress!
